"""Add space_number to Bookingg

Revision ID: 06a46dbc5020
Revises: 554c864005b1
Create Date: 2025-08-20 23:13:40.409403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a46dbc5020'
down_revision = '554c864005b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_capacity', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('meeting_capacity')

    # ### end Alembic commands ###
