"""Ajout de la colonne space_type

Revision ID: 23ed0f25730b
Revises: d3f6f8205fc1
Create Date: 2025-08-19 01:58:47.826162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ed0f25730b'
down_revision = 'd3f6f8205fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        # Modification 1: D'abord ajouter comme nullable
        batch_op.add_column(sa.Column('space_type', sa.String(length=20), nullable=True))
    
    # Modification 2: Mettre à jour les valeurs existantes
    op.execute("UPDATE booking SET space_type = 'private' WHERE space_type IS NULL")
    
    with op.batch_alter_table('booking', schema=None) as batch_op:
        # Modification 3: Puis modifier en NOT NULL
        batch_op.alter_column('space_type', nullable=False)

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')
    # ### end Alembic commands ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_number', sa.String(length=20), nullable=True))
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_capacity', sa.String(length=10), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.TEXT(), nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('space_type')

    # ### end Alembic commands ###
