"""Add space_number to Booking

Revision ID: 554c864005b1
Revises: 23ed0f25730b
Create Date: 2025-08-20 22:05:52.229500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554c864005b1'
down_revision = '23ed0f25730b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_number', sa.String(length=20), nullable=True))
        batch_op.alter_column('space_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('space_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('space_number')

    # ### end Alembic commands ###
