"""ajout created_by et updated_by à Booking

Revision ID: 68e16a6cbde3
Revises: 06a46dbc5020
Create Date: 2025-08-21 15:52:10.957780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e16a6cbde3'
down_revision = '06a46dbc5020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('updated_by')
        batch_op.drop_column('date_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
