"""ajout created_by et updated_by à Booking

Revision ID: d85e7872b552
Revises: 06a46dbc5020
Create Date: 2025-08-21 15:40:22.622442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85e7872b552'
down_revision = '06a46dbc5020'
branch_labels = None
depends_on = None



def upgrade():
    # Ajouter les colonnes avec des valeurs par défaut pour les lignes existantes
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))  # D'abord nullable=True
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    # Mettre à jour les colonnes `created_by` et `updated_by` pour les lignes existantes
    op.execute("UPDATE booking SET created_by = 1 WHERE created_by IS NULL")  # Remplacez 1 par un ID utilisateur valide
    op.execute("UPDATE booking SET updated_by = 1 WHERE updated_by IS NULL")  # Remplacez 1 par un ID utilisateur valide

    # Modifier la colonne `created_by` pour la rendre NOT NULL
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('created_by', nullable=False)

    # Ajouter les clés étrangères
    op.create_foreign_key(
        constraint_name='fk_booking_created_by_user',
        source_table='booking',
        referent_table='user',
        local_cols=['created_by'],
        remote_cols=['id']
    )
    op.create_foreign_key(
        constraint_name='fk_booking_updated_by_user',
        source_table='booking',
        referent_table='user',
        local_cols=['updated_by'],
        remote_cols=['id']
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date_updated')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
